app:
  name: "catchup-server"
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "catchup"
  require_ssl: false
http_client:
  timeout_millis: 10000
scraper_config:
  schedule: "0 */12 * * *"
services:
  irish_times:
    key: "irishtimes"
    base_url: "https://irishtimes.com"
    tag: "technology"
  hacker_news:
    key: "hackernews"
    base_url: "https://hn.algolia.com/api/v1/search?tags=front_page"
  dou:
    key: "dou"
    base_url: "https://dou.ua/lenta"
