app:
  name: "catchup-server"
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "catchup"
  require_ssl: false
supported_sources:
  irishtimes:
    key: "irishtimes"
  hackernews:
    key: "hackernews"
  dou:
    key: "dou"
http_client:
  timeout_millis: 10000